apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-html
  namespace: lab-3tier
data:
  index.html: |
    <!doctype html>
    <html>
      <head><meta charset="utf-8"><title>Lab 3-tiers</title></head>
      <body>
        <h1>Frontend (Nginx)</h1>
        <p>Backend API (service interne) : <a href="http://backend.lab-3tier.svc.cluster.local">backend.lab-3tier.svc.cluster.local</a></p>
        <p>Test backend via navigateur: (utilise plutôt un port-forward / ingress)</p>
      </body>
    </html>
